// GENERATED by tools/gen_c3_icons.py. The CoreS3's icons, and the dial's names mapped onto them.
// Include AFTER the dial's icon headers, in CoreS3 builds only.
#pragma once
#include "lvgl.h"

extern const lv_image_dsc_t c3_icon_voice;
extern const lv_image_dsc_t c3_icon_wifi;
extern const lv_image_dsc_t c3_icon_newproj;
extern const lv_image_dsc_t c3_icon_battery;
extern const lv_image_dsc_t c3_icon_brightness;
extern const lv_image_dsc_t c3_icon_lock;
extern const lv_image_dsc_t c3_icon_loop;
extern const lv_image_dsc_t c3_icon_reset;
extern const lv_image_dsc_t c3_icon_info;
extern const lv_image_dsc_t c3_icon_act_voice;
extern const lv_image_dsc_t c3_icon_act_loop;
extern const lv_image_dsc_t c3_icon_v_mic;
extern const lv_image_dsc_t c3_icon_v_rec;
extern const lv_image_dsc_t c3_icon_v_tick;
extern const lv_image_dsc_t c3_icon_v_orb;
extern const lv_image_dsc_t c3_icon_sparkle;
extern const lv_image_dsc_t c3_icon_sparkle_fill;
extern const lv_image_dsc_t c3_icon_globe;
extern const lv_image_dsc_t c3_icon_claude;
extern const lv_image_dsc_t c3_icon_codex;
extern const lv_image_dsc_t c3_icon_cursor;
extern const lv_image_dsc_t c3_icon_opencode;
extern const lv_image_dsc_t c3_icon_pi;
extern const lv_image_dsc_t c3_icon_muse;
extern const lv_image_dsc_t c3_icon_amp;
extern const lv_image_dsc_t c3_icon_kilo;
extern const lv_image_dsc_t c3_icon_grok;
extern const lv_image_dsc_t c3_icon_devin;
extern const lv_image_dsc_t c3_icon_commandcode;
extern const lv_image_dsc_t c3_icon_hermes;
extern const lv_image_dsc_t c3_icon_agy;
extern const lv_image_dsc_t c3_icon_copilot;
extern const lv_image_dsc_t c3_spinner_spoke_0;
extern const lv_image_dsc_t c3_spinner_spoke_1;
extern const lv_image_dsc_t c3_spinner_spoke_2;
extern const lv_image_dsc_t c3_spinner_spoke_3;
extern const lv_image_dsc_t c3_spinner_spoke_4;
extern const lv_image_dsc_t c3_spinner_spoke_5;
extern const lv_image_dsc_t c3_spinner_spoke_6;
extern const lv_image_dsc_t c3_spinner_spoke_7;
extern const lv_image_dsc_t c3_spinner_spoke_8;
extern const lv_image_dsc_t c3_spinner_spoke_9;
extern const lv_image_dsc_t c3_spinner_spoke_10;
extern const lv_image_dsc_t c3_spinner_spoke_11;
extern const lv_image_dsc_t *const c3_spinner_spokes[12];

#define icon_voice c3_icon_voice
#define icon_wifi c3_icon_wifi
#define icon_newproj c3_icon_newproj
#define icon_battery c3_icon_battery
#define icon_brightness c3_icon_brightness
#define icon_lock c3_icon_lock
#define icon_loop c3_icon_loop
#define icon_reset c3_icon_reset
#define icon_info c3_icon_info
#define icon_act_voice c3_icon_act_voice
#define icon_act_loop c3_icon_act_loop
#define icon_v_mic c3_icon_v_mic
#define icon_v_rec c3_icon_v_rec
#define icon_v_tick c3_icon_v_tick
#define icon_v_orb c3_icon_v_orb
#define icon_sparkle c3_icon_sparkle
#define icon_sparkle_fill c3_icon_sparkle_fill
#define icon_globe c3_icon_globe
#define icon_claude c3_icon_claude
#define icon_codex c3_icon_codex
#define icon_cursor c3_icon_cursor
#define icon_opencode c3_icon_opencode
#define icon_pi c3_icon_pi
#define icon_muse c3_icon_muse
#define icon_amp c3_icon_amp
#define icon_kilo c3_icon_kilo
#define icon_grok c3_icon_grok
#define icon_devin c3_icon_devin
#define icon_commandcode c3_icon_commandcode
#define icon_hermes c3_icon_hermes
#define icon_agy c3_icon_agy
#define icon_copilot c3_icon_copilot
#define spinner_spokes c3_spinner_spokes
