#!/usr/bin/env python3
"""The CoreS3's icons: every UI bitmap at 0.6x, the scale the CoreS3 draws the dial at (ui_screens.c PX()).

    python3 tools/gen_c3_icons.py        # writes main/ui/icons_c3.c and main/ui/icons_c3.h

Reads the dial's ARGB8888 icons straight from their C sources (icons_settings.c, icons_voice.c,
icons_engine.c, spinner_spokes.c) and resamples each with an alpha-weighted area average, so edges stay
soft and no colour bleeds out of transparent pixels. Done once, here, rather than by LVGL's image
transform, which would redo the work on every redraw and blur the result. icons_c3.h maps the dial's
names onto these for CoreS3 builds, so ui_screens.c names one set for both boards.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
UI = os.path.join(HERE, "..", "main", "ui")
SOURCES = ["icons_settings.c", "icons_voice.c", "icons_engine.c", "spinner_spokes.c"]
SCALE = 0.6

map_re = re.compile(r"static const uint8_t (\w+)_map\[\]\s*=\s*\{([^}]*)\};", re.S)
dsc_re = re.compile(r"const lv_image_dsc_t (\w+)\s*=\s*\{(.*?)\};", re.S)


def resample(px, w, h, nw, nh):
    """px: list of (b,g,r,a). Area-average with alpha weighting onto nw x nh."""
    out = []
    sx, sy = w / nw, h / nh
    for oy in range(nh):
        y0, y1 = oy * sy, (oy + 1) * sy
        for ox in range(nw):
            x0, x1 = ox * sx, (ox + 1) * sx
            ab = ag = ar = aa = area = 0.0
            iy = int(y0)
            while iy < y1 and iy < h:
                wy = min(y1, iy + 1) - max(y0, iy)
                ix = int(x0)
                while ix < x1 and ix < w:
                    wx = min(x1, ix + 1) - max(x0, ix)
                    wgt = wx * wy
                    b, g, r, a = px[iy * w + ix]
                    aw = a * wgt
                    ab += b * aw; ag += g * aw; ar += r * aw; aa += aw; area += wgt
                    ix += 1
                iy += 1
            if aa > 0:
                out.append((round(ab / aa), round(ag / aa), round(ar / aa), round(aa / area)))
            else:
                out.append((0, 0, 0, 0))
    return out


def main():
    icons = []
    for f in SOURCES:
        src = open(os.path.join(UI, f)).read()
        maps = {m.group(1): [int(v) for v in re.findall(r"\d+", m.group(2))] for m in map_re.finditer(src)}
        for d in dsc_re.finditer(src):
            name, body = d.group(1), d.group(2)
            if "ARGB8888" not in body:
                continue
            w = int(re.search(r"\.header\.w\s*=\s*(\d+)", body).group(1))
            h = int(re.search(r"\.header\.h\s*=\s*(\d+)", body).group(1))
            data = re.search(r"\.data\s*=\s*(\w+)_map", body).group(1)
            raw = maps[data]
            px = [tuple(raw[i:i + 4]) for i in range(0, w * h * 4, 4)]
            nw, nh = max(1, round(w * SCALE)), max(1, round(h * SCALE))
            icons.append((name, nw, nh, resample(px, w, h, nw, nh)))

    c = ['// GENERATED by tools/gen_c3_icons.py — the dial\'s icons at 0.6x for the CoreS3. Do not hand-edit.',
         '#include "lvgl.h"', '#include "icons_c3.h"', '']
    hdr = ['// GENERATED by tools/gen_c3_icons.py. The CoreS3\'s icons, and the dial\'s names mapped onto them.',
           '// Include AFTER the dial\'s icon headers, in CoreS3 builds only.', '#pragma once', '#include "lvgl.h"', '']
    for name, w, h, px in icons:
        flat = ",".join(str(v) for p in px for v in p)
        c.append(f"static const uint8_t c3_{name}_map[] = {{{flat}}};")
        c.append(f"const lv_image_dsc_t c3_{name} = {{ .header.magic = LV_IMAGE_HEADER_MAGIC, "
                 f".header.cf = LV_COLOR_FORMAT_ARGB8888, .header.w = {w}, .header.h = {h}, "
                 f".header.stride = {w * 4}, .data_size = sizeof(c3_{name}_map), .data = c3_{name}_map }};")
        hdr.append(f"extern const lv_image_dsc_t c3_{name};")
    spokes = sorted(n for n, *_ in icons if n.startswith("spinner_spoke_"))
    c.append("const lv_image_dsc_t *const c3_spinner_spokes[12] = { "
             + ", ".join(f"&c3_{n}" for n in sorted(spokes, key=lambda s: int(s.rsplit('_', 1)[1]))) + " };")
    hdr.append("extern const lv_image_dsc_t *const c3_spinner_spokes[12];")
    hdr.append("")
    for name, *_ in icons:
        if not name.startswith("spinner_spoke_"):
            hdr.append(f"#define {name} c3_{name}")
    hdr.append("#define spinner_spokes c3_spinner_spokes")
    open(os.path.join(UI, "icons_c3.c"), "w").write("\n".join(c) + "\n")
    open(os.path.join(UI, "icons_c3.h"), "w").write("\n".join(hdr) + "\n")
    print(f"{len(icons)} icons -> icons_c3.c")


if __name__ == "__main__":
    main()
