"""Small immutable Player icons; reuse the desktop's provider identities."""
from pathlib import Path
import math
import re
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[5]
OUT = ROOT / "devices/harness-device/firmware/main/ui/habitat/pro_player_icons.h"
icons = {}
for name, source in (("codex", "engine-icons/codex.png"),):
    icons[name] = Image.open(ROOT / "desktop/assets" / source).convert("RGBA").resize((24, 24), Image.Resampling.LANCZOS)
# The exact geometry of desktop/widgets/engine_identity.dart's Claude painter.
im = Image.new("RGBA", (96, 96))
draw = ImageDraw.Draw(im)
for i in range(4):
    angle = i * math.pi / 4
    dx, dy = 96 * .39 * math.cos(angle), 96 * .39 * math.sin(angle)
    points = [(48-dx,48-dy),(48+dx,48+dy)]
    draw.line(points, fill="#cc7c5e", width=9)
    for x,y in points: draw.ellipse((x-4.5,y-4.5,x+4.5,y+4.5), fill="#cc7c5e")
icons["claude"] = im.resize((24,24), Image.Resampling.LANCZOS)

# Use the desktop's pinned Lucide font, not a second set of hand-drawn controls.
lock = (ROOT / 'desktop/pubspec.lock').read_text()
version = re.search(r'  lucide_icons_flutter:.*?    version: "([^"]+)"', lock, re.S).group(1)
lucide = Path.home() / f'.pub-cache/hosted/pub.dev/lucide_icons_flutter-{version}'
source = (lucide / 'lib/lucide_icons.dart').read_text()
for name, glyph, size, color in (
    ('back','chevronLeft',32,'#191a18'),
):
    cp = int(re.search(r'static const IconData '+glyph+r' = const IconData\((\d+)',source).group(1))
    font = ImageFont.truetype(str(lucide / 'assets/lucide.ttf'),size*4)
    im = Image.new('RGBA',(size*4,size*4))
    draw = ImageDraw.Draw(im)
    x0,y0,x1,y1 = draw.textbbox((0,0),chr(cp),font=font)
    draw.text(((size*4-(x1-x0))/2-x0,(size*4-(y1-y0))/2-y0),chr(cp),font=font,fill=color)
    icons[name] = im.resize((size,size),Image.Resampling.LANCZOS)

# Desktop and TUI activity vocabulary and ten-frame, 100 ms braille sequence.
activity = (ROOT / 'desktop/lib/state/harness_activity.dart').read_text()
frames = re.findall(r"'([^']+)'", re.search(r'activitySpinnerFrames = \[(.*?)\];', activity, re.S).group(1))
marks = [('done', '✓', '#598a46'), ('question', '?', '#b58218'), ('failed', '✗', '#ab4239')]
marks += [(f'working_{i}', glyph, '#2597a3') for i, glyph in enumerate(frames)]
font = ImageFont.truetype('/System/Library/Fonts/Menlo.ttc', 24*4)
braille = ImageFont.truetype('/System/Library/Fonts/Apple Symbols.ttf', 28*4)
# Keep the braille cell fixed across frames, like a terminal's text baseline.
# Centering each frame's lit dots separately would make the whole cell jump.
boxes = [braille.getbbox(glyph) for glyph in frames]
cell = (min(b[0] for b in boxes), min(b[1] for b in boxes),
        max(b[2] for b in boxes), max(b[3] for b in boxes))
for name, glyph, color in marks:
    mark_font = braille if name.startswith('working_') else font
    im = Image.new('RGBA', (112,112))
    draw = ImageDraw.Draw(im)
    x0,y0,x1,y1 = cell if name.startswith('working_') else draw.textbbox((0,0),glyph,font=mark_font)
    draw.text(((112-x1+x0)/2-x0,(112-y1+y0)/2-y0),glyph,font=mark_font,fill=color)
    icons[name] = im.resize((28,28),Image.Resampling.LANCZOS)

lines = ['/* Generated by generate_player_icons.py. Lucide license: prototype/pro-companion/PLAYER-ICONS-LICENSE.txt */', '#pragma once']
for name, im in icons.items():
    pixels = list(im.getdata())
    rgb = [(r >> 3) << 11 | (g >> 2) << 5 | b >> 3 for r, g, b, _ in pixels]
    alpha = [a for _, _, _, a in pixels]
    for kind, ctype, data in (("pixels", "uint16_t", rgb), ("alpha", "uint8_t", alpha)):
        lines.append(f'static const {ctype} player_{name}_{kind}[]={{')
        lines += [','.join(str(v) for v in data[i:i + 24]) + ',' for i in range(0, len(data), 24)]
        lines.append('};')
    lines.append(f'static const ht_pro_bitmap_t player_{name}={{.pixels=player_{name}_pixels,.alpha=player_{name}_alpha,.width={im.width},.height={im.height},.revision=1}};')
lines.append('static const ht_pro_bitmap_t *const player_working[]={' + ','.join(f'&player_working_{i}' for i in range(len(frames))) + '};')
OUT.write_text('\n'.join(lines) + '\n')
print(OUT)
