#!/usr/bin/env python3
"""Pack the approved raster characters into registered, palette pose assets.

Runtime supplies continuous breathing, bends, ear/arm sway, bounce and blinks.
The source PNGs remain unmodified. Every cell retains its shared registration.
"""
from pathlib import Path
import hashlib
import json
import struct
import zlib
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SIZE = 320
NAMES = ('tim', 'spirit', 'moss')

def main():
    out = ROOT / 'generated'
    out.mkdir(exist_ok=True)
    blob = bytearray()
    frames = []
    for name in NAMES:
        source = ROOT / 'assets/living' / (name + '.png')
        atlas = Image.open(source).convert('RGBA')
        assert atlas.width == atlas.height and atlas.width % 3 == 0
        cell = atlas.width // 3
        for pose in range(9):
            x, y = pose % 3 * cell, pose // 3 * cell
            im = atlas.crop((x,y,x+cell,y+cell)).resize((SIZE,SIZE), Image.Resampling.LANCZOS)
            # This gallery has one fixed dark stage. Matting onto that native
            # backdrop preserves fine fur and glow without spending palette
            # entries on near-identical RGBA alpha levels.
            matte = Image.new('RGBA',im.size,'#101019')
            matte.alpha_composite(im)
            q = matte.convert('RGB').quantize(colors=192, method=Image.Quantize.MEDIANCUT)
            palette = q.getpalette('RGB')
            palette += [0] * (768-len(palette))
            palette[q.getpixel((0,0))*3:q.getpixel((0,0))*3+3] = [16,16,25]
            raw = bytearray()
            for i in range(256):
                r,g,b = palette[i*3:i*3+3]
                raw.extend(struct.pack('<H', (r>>3)<<11 | (g>>2)<<5 | b>>3))
            raw.extend(q.tobytes())
            data = zlib.compress(raw, 9)
            assert zlib.decompress(data) == raw
            frames.append(dict(character=name,pose=pose,offset=len(blob),length=len(data),
                               sha256=hashlib.sha256(raw).hexdigest()))
            blob.extend(data)
        print(name, len(blob), flush=True)
    header = ['/* Generated by generate_living.py; palette RGB565 on the fixed dark stage, then indices. */',
              '#pragma once', '#include <stdint.h>',
              f'#define PRO_LIVING_SOURCE {SIZE}',
              f'#define PRO_LIVING_RAW_BYTES {SIZE*SIZE+512}',
              'typedef struct { uint32_t offset, length; } pro_living_asset_t;',
              'static const pro_living_asset_t pro_living_assets[27] = {']
    header += ['{%d,%d},' % (f['offset'], f['length']) for f in frames]
    header += ['};', '']
    (out/'pro_living_assets.h').write_text('\n'.join(header))
    (out/'pro_living.pack').write_bytes(blob)
    (out/'living-manifest.json').write_text(json.dumps(dict(bytes=len(blob),size=SIZE,
        sha256=hashlib.sha256(blob).hexdigest(),frames=frames),indent=2)+'\n')
    print('living pack:', len(blob), 'bytes')

if __name__ == '__main__':
    main()
