#!/usr/bin/env node
/**
 * Writes src/lib/connectors/generated/*.ts from src/lib/connectors/assets: the catalog, the page's files
 * and the services' icons as data URLs, so cli.js carries them with no loader or asset file of its own.
 *
 *   node scripts/connector-assets.mjs          # after changing anything in assets/
 *   node scripts/connector-assets.mjs --check  # what the spec runs: fails when they differ
 *
 * src/lib/connectors/generated.spec.ts keeps the two in step.
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { join, extname, basename } from 'node:path'

const root = fileURLToPath(new URL('../src/lib/connectors/', import.meta.url))
const assets = join(root, 'assets')
const out = join(root, 'generated')
const header = '// Generated by scripts/connector-assets.mjs from src/lib/connectors/assets. Do not edit.\n'

export function render() {
  const catalog = JSON.parse(readFileSync(join(assets, 'catalog.json'), 'utf8')).connectors
  const icons = {}
  for (const name of readdirSync(join(assets, 'web/icons')).sort()) {
    const type = { '.png': 'image/png', '.svg': 'image/svg+xml' }[extname(name)]
    if (!type) continue
    icons[basename(name, extname(name))] = `data:${type};base64,${readFileSync(join(assets, 'web/icons', name)).toString('base64')}`
  }
  const page = Object.fromEntries(['index.html', 'page.js', 'style.css'].map(name => [name, readFileSync(join(assets, 'web', name), 'utf8')]))
  return {
    'catalog.ts': `${header}import type { CatalogItem } from '../catalog.js'\n\nexport const CATALOG_ITEMS: CatalogItem[] = ${JSON.stringify(catalog, null, 1)}\n`,
    'icons.ts': `${header}/** Each service's icon as a data URL, by code. */\nexport const ICONS: Record<string, string> = ${JSON.stringify(icons, null, 1)}\n`,
    'page.ts': `${header}/** The Connectors page's files, served by page.ts. */\nexport const PAGE_FILES: Record<string, string> = ${JSON.stringify(page, null, 1)}\n`,
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const files = render()
  if (process.argv.includes('--check')) {
    const stale = Object.entries(files).filter(([name, body]) => {
      try { return readFileSync(join(out, name), 'utf8') !== body } catch { return true }
    }).map(([name]) => name)
    if (stale.length) { console.error(`Out of date: ${stale.join(', ')}. Run node scripts/connector-assets.mjs`); process.exit(1) }
  } else {
    mkdirSync(out, { recursive: true })
    for (const [name, body] of Object.entries(files)) writeFileSync(join(out, name), body)
  }
}
