// Generated by scripts/gen_focus_faces.py. Do not edit.
#pragma once
#include "terminal.h"
extern const ht_pfont_t ht_lv_literata_20;
extern const ht_pfont_t ht_lv_literata_25;
extern const ht_pfont_t ht_lv_literata_med_26;
extern const ht_pfont_t ht_lv_literata_30;
extern const ht_pfont_t ht_lv_literata_36;
