#pragma once
// Generated by scripts/pod_gen_logos.py. Do not edit.
#include <stdint.h>

enum { POD_LOGO_NSIZES = 2, POD_LOGO_CHIP = 28, POD_LOGO_COVER = 72 };   // CHIP: inside the 36 px chip; COVER: every pet-less cover
extern const uint16_t pod_logo_sizes[POD_LOGO_NSIZES];   // ascending; every engine has one logo per size
